"""Initial migration

Revision ID: f1d2db65f3c8
Revises: 
Create Date: 2025-01-21 17:21:42.427119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d2db65f3c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_interview',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_role', sa.String(length=120), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mock_interview')
    # ### end Alembic commands ###
